create extension if not exists pgcrypto;

create table if not exists public.tickets (
  id uuid primary key default gen_random_uuid(),
  ticket_number text not null unique,
  name text not null,
  email text not null,
  subject text not null,
  message text not null,
  status text not null default 'open' check (status in ('open', 'answered', 'closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists tickets_created_at_idx on public.tickets (created_at desc);
create index if not exists tickets_lookup_idx on public.tickets (ticket_number, email);

create table if not exists public.ticket_replies (
  id bigint generated by default as identity primary key,
  ticket_id uuid not null references public.tickets(id) on delete cascade,
  sender text not null default 'admin' check (sender in ('admin')),
  body text not null,
  created_at timestamptz not null default now()
);

create index if not exists ticket_replies_ticket_idx on public.ticket_replies (ticket_id, created_at);

alter table public.tickets enable row level security;
alter table public.ticket_replies enable row level security;

-- No public policies are created. All access goes through the private
-- Netlify Functions using the Supabase service-role key.
